{% set name = "django-super-inlines" %}
{% set version = "0.2.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc2ee07efd28776d1295b3884f3c79e2efe8288115afc3e9dfae3c8de87378a6

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - django >=1.7.2
    - pip
    - python
  run:
    - django >=1.7.2
    - python

test:
  imports:
    - super_inlines
    - super_inlines.grappelli_integration
    - super_inlines.templatetags

about:
  home: https://github.com/BertrandBordage/django-super-inlines
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Adds useful features to inlines, such as the ability to nest them.

extra:
  recipe-maintainers:
    - bgruening
