{% set name = "django-super-inlines" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9c76086de1e9858e609b6ec8b0247e1a287bccaa0dbdd0b1602a0ca7d5b78ac

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - django >=1.7.2
    - pip
    - python
  run:
    - django >=1.7.2
    - python

test:
  imports:
    - super_inlines
    - super_inlines.grappelli_integration
    - super_inlines.templatetags

about:
  home: https://github.com/BertrandBordage/django-super-inlines
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Adds useful features to inlines, such as the ability to nest them.

extra:
  recipe-maintainers:
    - bgruening
